/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated/schedule/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsTeamsIndexRouteImport } from './routes/_authenticated/settings/teams/index'
import { Route as AuthenticatedSettingsRolesIndexRouteImport } from './routes/_authenticated/settings/roles/index'
import { Route as AuthenticatedSettingsGeneralIndexRouteImport } from './routes/_authenticated/settings/general/index'
import { Route as AuthenticatedScheduleTeamIndexRouteImport } from './routes/_authenticated/schedule/team/index'
import { Route as AuthenticatedScheduleMeIndexRouteImport } from './routes/_authenticated/schedule/me/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamsIndexRoute =
  AuthenticatedSettingsTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRolesIndexRoute =
  AuthenticatedSettingsRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralIndexRoute =
  AuthenticatedSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedScheduleTeamIndexRoute =
  AuthenticatedScheduleTeamIndexRouteImport.update({
    id: '/schedule/team/',
    path: '/schedule/team/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleMeIndexRoute =
  AuthenticatedScheduleMeIndexRouteImport.update({
    id: '/schedule/me/',
    path: '/schedule/me/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/schedule/me/': typeof AuthenticatedScheduleMeIndexRoute
  '/schedule/team/': typeof AuthenticatedScheduleTeamIndexRoute
  '/settings/general/': typeof AuthenticatedSettingsGeneralIndexRoute
  '/settings/roles/': typeof AuthenticatedSettingsRolesIndexRoute
  '/settings/teams/': typeof AuthenticatedSettingsTeamsIndexRoute
  '/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/schedule/me': typeof AuthenticatedScheduleMeIndexRoute
  '/schedule/team': typeof AuthenticatedScheduleTeamIndexRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralIndexRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesIndexRoute
  '/settings/teams': typeof AuthenticatedSettingsTeamsIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/schedule/me/': typeof AuthenticatedScheduleMeIndexRoute
  '/_authenticated/schedule/team/': typeof AuthenticatedScheduleTeamIndexRoute
  '/_authenticated/settings/general/': typeof AuthenticatedSettingsGeneralIndexRoute
  '/_authenticated/settings/roles/': typeof AuthenticatedSettingsRolesIndexRoute
  '/_authenticated/settings/teams/': typeof AuthenticatedSettingsTeamsIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/schedule/'
    | '/settings/'
    | '/schedule/me/'
    | '/schedule/team/'
    | '/settings/general/'
    | '/settings/roles/'
    | '/settings/teams/'
    | '/settings/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/schedule/me'
    | '/schedule/team'
    | '/settings/general'
    | '/settings/roles'
    | '/settings/teams'
    | '/settings/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
    | '/_authenticated/schedule/'
    | '/_authenticated/settings/'
    | '/_authenticated/schedule/me/'
    | '/_authenticated/schedule/team/'
    | '/_authenticated/settings/general/'
    | '/_authenticated/settings/roles/'
    | '/_authenticated/settings/teams/'
    | '/_authenticated/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/teams/': {
      id: '/_authenticated/settings/teams/'
      path: '/teams'
      fullPath: '/settings/teams/'
      preLoaderRoute: typeof AuthenticatedSettingsTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/roles/': {
      id: '/_authenticated/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof AuthenticatedSettingsRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general/': {
      id: '/_authenticated/settings/general/'
      path: '/general'
      fullPath: '/settings/general/'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/schedule/team/': {
      id: '/_authenticated/schedule/team/'
      path: '/schedule/team'
      fullPath: '/schedule/team/'
      preLoaderRoute: typeof AuthenticatedScheduleTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule/me/': {
      id: '/_authenticated/schedule/me/'
      path: '/schedule/me'
      fullPath: '/schedule/me/'
      preLoaderRoute: typeof AuthenticatedScheduleMeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsGeneralIndexRoute: typeof AuthenticatedSettingsGeneralIndexRoute
  AuthenticatedSettingsRolesIndexRoute: typeof AuthenticatedSettingsRolesIndexRoute
  AuthenticatedSettingsTeamsIndexRoute: typeof AuthenticatedSettingsTeamsIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsGeneralIndexRoute:
    AuthenticatedSettingsGeneralIndexRoute,
  AuthenticatedSettingsRolesIndexRoute: AuthenticatedSettingsRolesIndexRoute,
  AuthenticatedSettingsTeamsIndexRoute: AuthenticatedSettingsTeamsIndexRoute,
  AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
  AuthenticatedScheduleMeIndexRoute: typeof AuthenticatedScheduleMeIndexRoute
  AuthenticatedScheduleTeamIndexRoute: typeof AuthenticatedScheduleTeamIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
  AuthenticatedScheduleMeIndexRoute: AuthenticatedScheduleMeIndexRoute,
  AuthenticatedScheduleTeamIndexRoute: AuthenticatedScheduleTeamIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
